### ISSUE TITLE
discord bot !top command fails when message is too long

### ISSUE THREAD

**Issue by parlance-zz** [parlance-zz/g-diffuser-lib#15]
truncate top command output to 2000 chars

**Comment by sahaq** [comment]
One small suggestion that may require more work, but can also shrink top output; only show stats for the server the command comes from.

**Comment by parlance-zz** [comment]
> One small suggestion that may require more work, but can also shrink top output; only show stats for the server the command comes from.

Thank you, I hadn't considered that, in my testing I'm running on just one server 99% of the time.

I will incorporate this change.

**Comment by lootsorrow** [comment]
make sure to include a warning in that message to let the user know there are commands pending on other servers, since that will impact wait times, otherwise they will just think the thing is slow or broken if it tells them the queue only has 1 item but nothing is happening.

**Comment by lootsorrow** [comment]
add a warning message in the queue response indicating how many commands are queued across all the servers and channels the bot is in, otherwise a user might see a queue response that only shows a small number of commands queued up but nothing is happening and they will just think the bot is broken or slow or bad, and nobody wants that. except yacben.
