### ISSUE TITLE
Change -x param in discord bot

### ISSUE THREAD

**Issue by parlance-zz** [parlance-zz/g-diffuser-lib#43]
Negative values should trigger repeat mode ad infinitum (or up to max repeat limit), until !stop is run.

Do not show repeated commands in the queue more than once.

**Comment by lootsorrow** [comment]
instead of:

`Okay @parlance, here's your queue... 
1: [5:49:37 PM]  @parlance  !t2i chrono trigger -x 4 (waiting)
2: [5:49:37 PM]  @parlance  !t2i chrono trigger -x 4 (waiting)
3: [5:49:37 PM]  @parlance  !t2i chrono trigger -x 4 (waiting)
4: [5:49:37 PM]  @parlance  !t2i chrono trigger -x 4 (waiting)'

`Okay @parlance, here's your queue... 
1: [5:49:37 PM]  @parlance  !t2i chrono trigger -x 4 (waiting) - # remaining`
where # would show however many "charges" of that initial command are still waiting to be executed
